[build]
  command = "npm run build" 
  publish = "dist"

[[redirects]]
  from = "/puzzles/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
